name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build package with Maven
        run: mvn clean package

      - name: Build Docker image
        run: |
          sudo docker build -t ppraveen11/javaweb:${{ github.run_number }} .

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWD }}" | docker login -u ppraveen11 --password-stdin

      - name: Push image to Docker Hub
        run: |
          sudo docker push ppraveen11/javaweb:${{ github.run_number }}

      - name: Deploy WEBAPP in dev env
        run: |
          sudo docker rm -f javawebapp || true
          sudo docker run -d -p 1234:8080 --name javawebapp ppraveen11/javaweb:${{ github.run_number }}

      - name: Deploy WEBAPP in QAT/TEST env
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@43.205.196.152 "sudo docker rm -f javawebapp || true && sudo docker run -d -p 1234:8080 --name javawebapp ppraveen11/javaweb:${{ github.run_number }}"

      - name: QAT_TEST
        run: |
          echo "hello its QAT"

      - name: User input for approval
        run: |
          echo "Action was aborted."

      - name: Deploy WEBAPP in prod env
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@13.234.114.208 "ssh ec2-user@13.232.51.114 sudo kubectl delete deployment javawebapp && sudo kubectl create deployment javawebapp --image=ppraveen11/javaweb:${{ github.run_number }} && sudo kubectl apply -f webapsvc.yml && sudo kubectl scale deployment javawebapp --replicas=5"
